export const data = [
  {
    id: 72,
    user_id: 41187,
    name: "Ramil Murtuzov",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1731426172.jpg",
    contact_type: "instagram",
    contact: "@ramil.murtuzov",
    body: "Salam. Mən Ramil Murtuzov. 4 aydır Weecoins & Weecomi İnternational şirkətinin üzvüyəm. Bu şirkətdən Weecoins Premium adlı kripto pul əldə etmişəm. Və bu şirkətdən çox razıyam. Çünki bu kripto pulu aldığım gündən etibarən, şirkət mənə gündəlik olaraq, aldığım paketə uyğun kripto pul verir. Həmçinin mənə bu şirkətin biznes tərəfini, yəni Network marketinqi təklif edir. Network marketinqlə məşğul olmaqla xəyallarımızı gerçəkləşdirə bilirik. Əlavə olaraq, şirkətin Weesale.shop adlı ticarət səhifəsi və Weezard adlı oyun səhifəsi mövcuddur. Bu səhifələrdən də istifadə edərək Weecoins kripto pulları qazana bilərsiniz. Bir sözlə Weecomi İnternational-da olmaqla xəyallarınızı gerçəkləşdirə bilərsiniz. Elə isə durmayın, siz də hərəkətə keçin və xəyallarınızı gerçəkləşdirməyə başlayın. Bu yolda sizlərə uğurlar arzulayıram.",
    created_at: "2024-10-08 20:49:05",
    updated_at: "2024-10-08 20:49:05",
    is_approved: 1,
    language: "az",
  },
  {
    id: 64,
    user_id: 44292,
    name: "Tamerlan Qarayev",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1726826911.jpg",
    contact_type: "instagram",
    contact: "qaraaeev",
    body: "Mənə bunu çox yaxın bildiyim Cavad məsləhət gördü və məndə qoşuldum. Ancaq heçnə bilmirdim. Sonradan liderim Vüqar bəy sağolsun mənə öyrətməyə başladı. Hal-hazırda müəyyən qədər biliyim var bu sahədə. Fikirləşirəm ki çox yaxşıki qoşulmuşam çünki yeni insanlar tanıdım, gözəl kollektiv var və mənim buna çox ehtiyacım vardı. Burda olmaqdan çox xoşbəxtəm.",
    created_at: "2024-10-07 21:40:48",
    updated_at: "2024-10-07 21:40:48",
    is_approved: 1,
    language: "az",
  },
  {
    id: 65,
    user_id: 43178,
    name: "Zahid Azizov",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1726174625.jpg",
    contact_type: "instagram",
    contact: "Azizovzahid83",
    body: "Mən Zahid azizov 19.08.2024 cü ildə bu biznesə dəyərli Dostum Qardaşım Natiq Namiqbəyli tərəfindən dəvət almışam və böyük  bir həvəslə işə başlamışam artıq ekib qurub qazanc əldə edirəm və burada olduguma cox xoşbəxtəm dəstəyinə görə  Natiq qardaşıma təşəkkür  edirəm Weecoinslə butun hədəflərimə inanıram.Bu möhtəşəm proje ücün Hamza Özkan Cıbıra  minnətdaram.",
    created_at: "2024-10-07 21:45:57",
    updated_at: "2024-10-07 21:45:57",
    is_approved: 1,
    language: "az",
  },
  {
    id: 70,
    user_id: 45002,
    name: "Mirzayeva Rena",
    surname: "",
    image: null,
    contact_type: "instagram",
    contact: "Rena Otter99600",
    body: "Weecoins sirkəti ilə tanişliqim cəmi 1 həftədir. Lakin bu şirkətin iş prinsipinə , düzgünlüyünə inanaraq bu yola çıxdım. Qarşıda bizi daha böyük mövqelər fəth etmək və arzuları reallaşdırmaq üçün  ümid dolu, uzun və şərəfli yol gözləyir. Sevgilərlə ...",
    created_at: "2024-10-08 11:14:43",
    updated_at: "2024-10-08 11:14:43",
    is_approved: 1,
    language: "az",
  },
  {
    id: 83,
    user_id: 36642,
    name: "Elnut Miriyev",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1736139676.jpg",
    contact_type: "phone",
    contact: "702332545",
    body: "weecoins premium kriptovalyutanı almağı mənə dosdum tövsiyə  etdi  baxdım gördüm cox böyük projelərə və ekosistəmə sahib bir kriptodu qəbul etdim yatırım etdim bu gün kü gündə cox gözəl qazanc əldə edirəm, hər kəsə məsləhət görürəm",
    created_at: "2024-12-02 11:52:10",
    updated_at: "2024-12-02 11:52:10",
    is_approved: 1,
    language: "az",
  },
  {
    id: 84,
    user_id: 28072,
    name: "Roya Agammedova",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1721113948.jpg",
    contact_type: "instagram",
    contact: "a.r.roya",
    body:
      "Merhaba.Benim hikayem uzucu amma paylasmaq istedim.Ben Weecoinsle kardesim sayesinde tanisdim.Ben onun Weecoinse ne kadar inandigini \r\n" +
      " Weecoinsle hayatinin nasil deyiseceyinin sahidi oldum.O simdi hayatda deyil amma , beni sizinle tanistirdi, ben burda oldugum icin cok sansliyim.Bence WeeCoins insanlarin hayatina dokuna biliyor🤗",
    created_at: "2024-12-08 20:56:26",
    updated_at: "2024-12-08 20:56:26",
    is_approved: 1,
    language: "az",
  },
  {
    id: 66,
    user_id: 30190,
    name: "Aybeniz Aliyeva",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1722692945.jpg",
    contact_type: "no_contact",
    contact: "Bilgileriniz paylaşılmıyor.",
    body: "Mən Aybeniz Əliyeva 2023 cü ilin 15 avqustunda Weecomi şirkətinə dəvət aldım və həmin anda dəyərləndirin 66 yaşım var çox xoşbəxtəm ki bu şirkətdəyəm . İllərdən sanki bu işi gözləmişəmmiş qarşıma cıxdi  Məqsədim  illərdən həyata keçməyən arzularımi həyata keçirmək  hədəfim isə böyükdür Bütün varlıqımla inanıram ki hədəfinə catacam Həmzə bəyi çox sevirəm  coxsaqolsun ki ümidimiz qırılan yerdən həyatımıza daxil olub bizi xoşbəxt etdi Weecoins aşkdır!!!",
    created_at: "2024-10-07 21:50:21",
    updated_at: "2024-10-07 21:50:21",
    is_approved: 1,
    language: "az",
  },
  {
    id: 68,
    user_id: 21197,
    name: "Ruxsara Haciyeva",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1728327091.jpg",
    contact_type: "instagram",
    contact: "rufanaqadjiyeva",
    body: 'Men Haciyeva Ruxsare 2 ildirki bu şirketdeyem.Ilk başda ciddi yanaşmasamda.,bir qeder sonra şirketin ferqliliyini ve ciddiliyini qebullandim.Bir çox şirkətlərde calişmagima baxmayaraq..davamlı işlememişem .Cünki her ay balans ücün mütleqki,məhsul almalı olurduq ve bu mene çəkici gəlmirdi.Bu şirketin çox fərqli müsbet xüsusiyyətləri olduğu ücün burdayam .Başkanimiz Özkan bey kriptovalyuta arenasında öz desti xettiyle seçilir .Bizlər də her zaman başkanimizin yanındayiq.Bu şirkətdə var olduğum ücün Hamze bəyə və məni bura gətirən bacim Şahsənəm xanıma sonsuz minnətdarlığımı bildirirəm."Weecomi Weecoins International"bizim secimimizdir.Bize ugurlar!!!!!!!',
    created_at: "2024-10-07 22:44:43",
    updated_at: "2024-10-07 22:44:43",
    is_approved: 1,
    language: "az",
  },
  {
    id: 71,
    user_id: 15927,
    name: "Kamil Taghiyev",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1674739048.jpg",
    contact_type: "no_contact",
    contact: "Bilgileriniz paylaşılmıyor.",
    body: "Salam hervaxtiniz xeyir deyerli patniorlar. Adim Kamil 37 yasim var eslen Sabirabad rayonundanam bu sirketde calismaga baslamamisdan qabaq yasdigim rayondan Baki seherine kend teserufat mallari getirib satirdiq qazanc olsada cox cetin idi gece yuxusuz qalmaq masinla yol surmek ve nehayett 2021 ci ilde Qardasim Paşa Paşayev terefinden Weecomi International sirkerine qeydiyyat olmusam hami kimi mende bu sirkete inanmamisam meni taniyanlar hamisi bilirki men Azerbaycanda yerlesen Bas ofisde bir nece ay Tiktok da paylasilan Videolara baxib zaman itirmisem. Allah canin sag elesin Terlan ismayilovun cunki 21.09.2022 ci il tarixde yenede kohne qayda ile ofisdeyem Tiktoka baxiram Terlan bey ofise girdi ve ele bir yerimek yeridiki mende ona qarsi paxilliq hissi oyandi ve mende bu isi baslayacam ve yaxsi pul qazanacam deyib ayaga qalxdim hemin gunu bir nefer 50$ nan qeydiyyat etdim bibim oglu qeydiyyat oldu yeznem qeydiyyat oldu hal hazirda yeterli qeder komanda qurmusam tebiki asan olmadi amma azda olsa nelerese nail olmusam catmadigim meqsedler var insallah olarin ustunde isleyirem insallah tez bir zamanda yeni bir meqsedime catacam Allah cekilen herbir zehmetin behresin verendir. MEQSEDSIZ INSAN DERYADA YELKENSIZ GEMIYE BENZER. KULEK HANSI ISTIQAMETDE ESERSE GEMIDE O ISTIQAMETE YON ALAR! CALISIN MEQSEDLERINIZI TEYIN EDIN.",
    created_at: "2024-10-08 11:52:59",
    updated_at: "2024-10-08 11:52:59",
    is_approved: 1,
    language: "az",
  },
  {
    id: 85,
    user_id: 47065,
    name: "Qurbanova Vusale",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1734895583.jpg",
    contact_type: "no_contact",
    contact: "Bilgileriniz paylaşılmıyor.",
    body: "Bir defe pul yatirim ederek. Hec bir satis etmek yox. Pille dusmek yox",
    created_at: "2024-12-23 09:00:25",
    updated_at: "2024-12-23 09:00:25",
    is_approved: 1,
    language: "az",
  },
  {
    id: 78,
    user_id: 44167,
    name: "Ramazan Adilov",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1724784347.png",
    contact_type: "no_contact",
    contact: "Bilgileriniz paylaşılmıyor.",
    body: '"Komfort zonası" sadəcə inkişafınız üçün heç bir şey etmək istəmədiyiniz bir vəziyyətdir. Düşünürsən ki, orada çətinlik və problem olmadan yaşamaq daha asan olacaq. Ancaq əslində bu, ən təhlükəli vəziyyətdir, çünki həyatda özümüzü daha da böyük çətinliklərə məruz qoyuruq. Həyatın zərbələri bir-birinin ardınca gələcək, təcrübəsizliyimiz və zəif düşüncələrimiz ucbatından onlara qarşı dura bilməyəcəyik. Siz də eyni fikirdəsinizsə, dəstək olun -👍🏻',
    created_at: "2024-11-25 17:47:43",
    updated_at: "2024-11-25 17:47:43",
    is_approved: 1,
    language: "az",
  },
  {
    id: 82,
    user_id: 36642,
    name: "Elnut Miriyev",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1736139676.jpg",
    contact_type: "phone",
    contact: "702332545",
    body: "weecoins premium kriptovalyutanı almağı mənə dosdum tövsiyə  etdi  baxdım gördüm cox böyük projelərə və ekosistəmə sahib bir kriptodu qəbul etdim yatırım etdim bu gün kü gündə cox gözəl qazanc əldə edirəm, hər kəsə məsləhət görürəm",
    created_at: "2024-12-02 11:52:10",
    updated_at: "2024-12-02 11:52:10",
    is_approved: 1,
    language: "az",
  },
  {
    id: 74,
    user_id: 42275,
    name: "Talib Bayramov",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1728215693.png",
    contact_type: "no_contact",
    contact: "Bilgileriniz paylaşılmıyor.",
    body: "Ve men icaze verirem direk öz adımda açıq aydın düşsün çünki böyük sehf etmişem iller once deveti qebul etmemişem. Birc alıb işe başlamaqdanda utanmıram. Bir daha sponsorum Sevinc Abdullayeva xanima minnetdaram. Hörmetle Talıb Bayramov Gence 🤝✊",
    created_at: "2024-10-08 22:35:02",
    updated_at: "2024-10-08 22:35:02",
    is_approved: 1,
    language: "az",
  },
  {
    id: 73,
    user_id: 42275,
    name: "Talib Bayramov",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1728215693.png",
    contact_type: "no_contact",
    contact: "Bilgileriniz paylaşılmıyor.",
    body: "Men Talıb Bayramov Gence şeherinde Kikboksinq idman novü üzre muellim işleyirem. Kripto paradan heç bir anlayışım olmayib, network marketinq sozunu bele bilmemişem ne demekdir. Meni 2022ci ilde  Sevinc xanim devet etdi bu şirkete ve men yox menlik deyil dedim. Qoşulmadim getdim. Ve sora birde devet etdi geldim sunuma dinledim ama qoşulmaq isdedim heqiqeten pulum yox idi. Aĝ paketle meni Liderim Sevinc xanim qoşdu oz pulu ile 200 $ dollar ile başladim. Ve bu gunki gun sponsorum Sevinc xanima minnetdaram ki o meni bu işe qoşduĝu üçün. Men borcumuda qaytardim Liderime ve paketim hal hazirda qırmızı paket etmiwem. Ve üstegel oĝlum ve ailem üçünde paketler açmışam. Bu şirketde 3 ayda 4350$ pul qazanmışam. Ve bunun üçün sexsen sponsoruma minnetdaram. Ve çox peşimanam 2022ci ilde qoşulmadıĝım üçün.",
    created_at: "2024-10-08 22:30:16",
    updated_at: "2024-10-08 22:30:16",
    is_approved: 1,
    language: "az",
  },
  {
    id: 67,
    user_id: 26900,
    name: "Vuqar Elekberov",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1715034146.jpg",
    contact_type: "facebook",
    contact: "Vuqar Elekberov",
    body:
      "Herkese burdan salamlarımı bildirirem.\r\n" +
      "Men Vuqar Elekberov bildirmek isdeyirem ki WEECOINS şirketine gelenecen cox çetinliklerden keçdim.Demek olarki çox yerlerde çalışsamda cibi boş bir heyat sürerdim. Ailemi zorla dolandırardım.Her gece eve gedende uşaqların menden isdedikler xırda bir birşeyleri alıb apara bilmirdim.artıq tenge gelmişdim .qerar vermişdim ki Azerbaycanı terkedem.Devletde su idaresinde 250-sonrada 345 manata aylıq işleyirdim.pulun az olduguna göre  axşamlar işden gelib taksilikle meşgul olurdum.Yenede isdediyim kimi dolana bilmirdim.Artıq qerara gelmişdimki Azerbaycanı terkedem.dolanşıq az oldugundan çaremi başqa ölkede axdarırdım.bir gün dosdum Arzu mene bir iş oldugunu söyledi.Sadece 90 manatla başlayıb ela bir qazanc elde edə bilersen dedi.mende ona gülüb 90 manatla iş olar  dedim.Sen deme olarmış.90 manat verib Weekoins şirketinin üzvü oldum.WEECOİNS şirketi heqiqetende isdediyin puldan artıgını qazandırır.çox şadamki bele birşirketdeçalışıram .Əsası odur ki artıq Azerbaycanı terk etmek isdemirem ve ailemin yanında utanmıram.artıq uşaqların her bir isdeyini artıqlamasınla yerine yetrirem.isdediyimdende çox qazana bilirem.Me WEEKOINS şirketinin başqanı olan HEMZE ÖZKAN CIBIR beye öz dərin təşəkkürümü bildirirəm.Nə yaxşı ki bele bir şirket açmış.Bizlerde bu işden artıqlamasınla yararlana bildik",
    created_at: "2024-10-07 22:23:18",
    updated_at: "2024-10-07 22:23:18",
    is_approved: 1,
    language: "az",
  },
  {
    id: 79,
    user_id: 44167,
    name: "Ramazan Adilov",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1724784347.png",
    contact_type: "no_contact",
    contact: "Bilgileriniz paylaşılmıyor.",
    body:
      "**Мои лидеры, Товарищи и большая семья! ** 🌍🔥\r\n" +
      "Бесконечное спасибо всем лидерам, которые верили в нас и поддерживали с самого начала! Сильный интерес, проявленный сегодня к продвижению наших новых экосистем в Азербайджане, вновь подтвердил нашу веру в успех. С вами наша цель 2030 и дальше! 🌟\r\n" +
      "Помните, что успех достигается не только на солнечных дорогах, но и шагая к свету в темноте. С каждым шагом, который мы делаем в этом путешествии, мы будем касаться жизней тысяч людей, мы внесем большие перемены в мире. Мы семья и вместе мы преодолеем любые испытания! 💪🌟\r\n" +
      "**Цель большая, путь долгий, но мы вместе! ** 💫 \r\n" +
      "Шаг за шагом мы неуклонно движемся к своим целям. В Weecoins & Weecoins Premium мы не останавливаемся, пока мир не признает нас и не достигнем наших целей!\r\n" +
      "Самое время объединить усилия, чтобы приблизиться к нашим целям!",
    created_at: "2024-11-25 17:49:51",
    updated_at: "2024-11-25 17:49:51",
    is_approved: 1,
    language: "az",
  },
  {
    id: 69,
    user_id: 26063,
    name: "Kënul Kerimova",
    surname: "",
    image: "https://backoffice.weecoins.org/user-image/profile-1720002050.jpg",
    contact_type: "no_contact",
    contact: "Bilgileriniz paylaşılmıyor.",
    body: "Ben  Rossiyadan bakıya dönüş etdikdən sonra  is axtarmağa   başladım  nereye gettim beni ise qöturmediller  və mən Weecoinse  devet, Aldim birinci qun hec bir sey anlamafim ve benim param yox idi .Ben,Zara  xanima dedemki ustumde ancag 20 gram gizilim var yardim et bunu Lambarda  qoyag  Zara Xanim yardim etti  ben 500 dollara la sirkete kayd oldum cox mutluyum bu sirketdeyem cox qozel kazandim gizilimi Lambartdan qoturdum Benim ablam  Russiyadan  Weecoinse katildi  hazirda  4 otakli ev aldi  wcs ile hal hazirda calisiyoruz ve burdan Masin almak isfiyorum insallah alaram Weecoinsle cox deyisdik Biz cox sansliyik ki burdayik kim heyatini deyismek isdeyir Weecoinse gelsin Baskanimizada cox minatdarik Tewekurlerki  bu sirket var",
    created_at: "2024-10-07 22:46:32",
    updated_at: "2024-10-07 22:46:32",
    is_approved: 1,
    language: "az",
  },
];
